### ISSUE TITLE
Modificar la inclusión del Framework Bootstrap y la librería JQuery para trabajar con versiones locales para agilizar el testing

### ISSUE THREAD

**Issue by lucas9005** [Unicen-Tupar/lruggiero#9]

**Comment by facuninni** [comment]
Estas codeando lucas?jajaja

-----Mensaje original-----
De: "Lucas Ruggiero" notifications@github.com
Enviado: ‎08/‎09/‎2015 12:51
Para: "Unicen-Tupar/lruggiero" lruggiero@noreply.github.com
Asunto: [lruggiero] Modificar la inclusión del Framework Bootstrap y la librería JQuery para trabajar con versiones locales para agilizar el testing (#9)

**Comment by lucas9005** [comment]
No, manzana jajaja
